### ISSUE TITLE
Что такое -1? Вынесите в отдельную переменную и дайте значащее имя

### ISSUE THREAD

**Issue by coursar** [Timmeze/Pycourse#4]
https://github.com/Timmeze/Pycourse/blob/f4053e8a334d1b290c0baf579ed293fb9c372012/lib.py#L7

**Comment by Timmeze** [comment]
Исправлено в новой версии

**Comment by coursar** [comment]
Если исправляете, то в комментарии к коммиту в PyCharm пишете "fixes #4. Исправлено. Добавлена переменная такая-то". При push'е это автоматически закрывает issue.
